name: quizwiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  animated_text_kit: ^4.2.2
  stacked_themes: ^0.3.12
  flutter_dotenv: ^5.1.0
  animate_do: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  html: ^0.15.4
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  connectivity_wrapper: ^1.1.4


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - assets/json/
  - .env

